# DIRECTORIES
assembly_dir: '/data6/bio/TFM/assembly'
assnake_db: '/data5/bio/databases/assnake'
fna_db_dir: '/data5/bio/databases/fna/'
run_dir: ''
cogs_dir : '/data5/bio/databases/ANVIO-COGs/'
conda_prefix: '/data4/bio/fedorov/assnake_conda/'
assnake_install_dir: '/data4/bio/fedorov/assnake_dev'
dada2_dir: '/data6/bio/TFM/dada2'

# TEST DATASET
test_df_prefix: '/data6/bio/TFM/datasets'
test_df_name: 'mg_test'

# DATABSES
BLAST_NCBI_NT: '/data5/bio/runs-jeniaole/tools/NCBI_nt'
NCBI_TAX: '/data5/bio/runs-jeniaole/tools/NCBI_tax'
CHECKM: '/data5/bio/databases/checkm'
QIIME2_SILVA99: '/data5/bio/databases/qiime2/silva-132-99-nb-classifier.qza'
QIIME2_GG99: '/data5/bio/databases/qiime2/gg-13-8-99-nb-classifier.qza'
CAT_BAT_DB: '/data5/bio/databases/CAT_BAT/CAT_prepare_20190108/2019-01-08_CAT_database'
CAT_BAT_TAXA: '/data5/bio/databases/CAT_BAT/CAT_prepare_20190108/2019-01-08_taxonomy'
# SOFTWARE
java.bin: '/srv/common/opt/jdk1.8.0_91/bin/java'
megahit.bin: '/data6/bio/TFM/soft/megahit/megahit'
bwa.bin : '/srv/common/bin/bwa'
samtools.bin: '/srv/common/bin/samtools'
anvio.bin : '/data4/bio/fedorov/miniconda3/envs/anvio5/bin/'

trimmomatic:
    bin: "/data6/bio/TFM/soft/Trimmomatic-0.36/trimmomatic-0.36.jar"

fastqc.bin: '/data6/bio/TFM/soft/FastQC/fastqc'


bbduk: '/data6/bio/TFM/soft/bioinf/mapping/bbmap-38.34/bbduk.sh'

bbmap.bin: '/home/fedorov/tools/bbmap/bbmap.sh'

bowtie2.bin: /srv/common/bin/bowtie2
bowtie2-build.bin: /srv/common/bin/bowtie2-build
bowtie2.additional.params: -k 1 
bowtie2.threads: '20'





gatk.jar : '/data7a/bio/BacGenomeSoft/GenomeAnalysisTK.jar'

picard.jar : '/data7a/bio/BacGenomeSoft/picard.jar'
#java.bin : '/home/fedorov/tools/java/jre1.8.0_161/bin/java' 

centrifuge:
    bin: '/data6/bio/TFM/soft/bioinf/centrifuge-1.0.4-beta/'
    # bin : '/data5/bio/runs-fedorov/tools/centrifuge/centrifuge/'
    index : '/data5/bio/databases/centrifuge/p+h+v/p+h+v'
kraken:
    v1.1: '/data6/bio/TFM/soft/bioinf/taxa/kraken-1.1/kraken'
    db:
        minikraken4GB: '/data6/bio/TFM/databases/kraken/minikraken_20171013_4GB'

kraken.bin: '/data7a/bio/runs-lutsenko/kraken/kraken'
kraken.db.human: '/data7a/bio/BacGenomeSoft/tmp/metagenome/human_db'
kraken.db.gb: '/data5/bio/runs-jeniaole/kraken/kr.db'


FindFungi:
    v0.23.3:
        consensus: '/data6/bio/TFM/pipeline/bin/scripts/FindFungi/Kraken32-to-Consensus.py'
        taxids: '/data6/bio/TFM/pipeline/bin/scripts/FindFungi/Fungal-Taxids.txt'
min_contig_size : 1000





prodigal: '/data5/bio/runs-fedorov/tools/prodigal_2.6.3/prodigal'

hmmer: 
    folder: '/data5/bio/runs-fedorov/tools/hmmer/hmmer-3.1b2-linux-intel-x86_64/binaries/'
    pfam: '/data5/bio/runs-fedorov/tools/hmmer/db/Pfam-A.hmm'
    
MetaPhlAn2:
    mpa_v20_m200: '/data5/bio/databases/MetaPhlAn2/mpa_v20_m200/mpa_v20_m200.pkl'
    BOWTIE2DB: '/data5/bio/databases/MetaPhlAn2/mpa_v20_m200'

    mpa_v29: '/data5/bio/databases/MetaPhlAn2/mpa_v29_CHOCOPhlAn_201901/mpa_v29_CHOCOPhlAn_201901.pkl'
    mpa_v29_bt: '/data5/bio/databases/MetaPhlAn2/mpa_v29_CHOCOPhlAn_201901'
METAPHLAN2: '/data3/bio/biouser/tools/metaphlan2/metaphlan2.py'
MPA_PKL: '/data3/bio/biouser/tools/metaphlan2/db_v20/mpa_v20_m200.pkl'
BOWTIE2DB: '/data3/bio/biouser/tools/metaphlan2/db_v20/mpa_v20_m200'