software:
    snakemake_folder: '/data6/bio/TFM/pipeline'

bbmap.bin: '/home/fedorov/tools/bbmap/bbmap.sh'

bowtie2.bin: /srv/common/bin/bowtie2
bowtie2-build.bin: /srv/common/bin/bowtie2-build
bowtie2.additional.params: -k 1 
bowtie2.threads: '20'

samtools.bin: '/srv/common/bin/samtools'

megahit.bin: '/data5/bio/runs-fedorov/tools/megahit/megahit'

bwa.bin : '/srv/common/bin/bwa'

gatk.jar : '/data7a/bio/BacGenomeSoft/GenomeAnalysisTK.jar'

picard.jar : '/data7a/bio/BacGenomeSoft/picard.jar'
#java.bin : '/home/fedorov/tools/java/jre1.8.0_161/bin/java' 
java.bin: '/srv/common/opt/jdk1.8.0_91/bin/java'

centrifuge:
    bin : '/data5/bio/runs-fedorov/tools/centrifuge/centrifuge/'
    index : '/data5/bio/runs-fedorov/tools/centrifuge/centrifuge-1.0.3-beta/p+h+v/p+h+v'
    v1.0.4-beta: '/data6/bio/TFM/soft/bioinf/centrifuge-1.0.4-beta/'

kraken.bin: '/data7a/bio/runs-lutsenko/kraken/kraken'
kraken.db.human: '/data7a/bio/BacGenomeSoft/tmp/metagenome/human_db'
kraken.db.gb: '/data5/bio/runs-jeniaole/kraken/kr.db'

min_contig_size : 1000

anvio.bin : '/data6/bio/TFM/soft/miniconda3/envs/anvio5/bin/'
cogs.dir : '/data5/bio/runs-fedorov/tools/anaconda3/envs/anvio4/cogs/'

python.bin : '/home/fedorov/miniconda3/bin/python'

samtools.bin: '/data5/bio/runs-fedorov/tools/anaconda3/envs/anvio4/bin/samtools'

trimmomatic:
    bin: "/data6/bio/TFM/soft/Trimmomatic-0.36/trimmomatic-0.36.jar"
    adapters: '/data5/bio/runs-fedorov/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa'
    params: "2:30:7:2 TRAILING:28 SLIDINGWINDOW:10:25 MAXINFO:90:0.3 AVGQUAL:25 MINLEN:65"
    #params: "3:30:7:2 CROP:250 MAXINFO:160:0.3 MINLEN:50"

fastqc.bin: '/data5/bio/runs-fedorov/tools/FastQC/fastqc'

prodigal: '/data5/bio/runs-fedorov/tools/prodigal_2.6.3/prodigal'

hmmer: 
    folder: '/data5/bio/runs-fedorov/tools/hmmer/hmmer-3.1b2-linux-intel-x86_64/binaries/'
    pfam: '/data5/bio/runs-fedorov/tools/hmmer/db/Pfam-A.hmm'
    
METAPHLAN2: '/data3/bio/biouser/tools/metaphlan2/metaphlan2.py'
MPA_PKL: '/data3/bio/biouser/tools/metaphlan2/db_v20/mpa_v20_m200.pkl'
BOWTIE2DB: '/data3/bio/biouser/tools/metaphlan2/db_v20/mpa_v20_m200'
