fastq_gz_file_wc: '{prefix}/{df}/reads/{preproc}/{sample}/{sample}_{strand}.fastq.gz'
fastq_file:       '{prefix}/{df}/reads/{preproc}/{sample}/{sample}_{strand}.fastq'
md5_fastq_gz:     '{prefix}/{df}/reads/{preproc}/{fs_name}/profile/{fs_name}_{strand}.md5'

fastqc_data_wc:   '{prefix}/{df}/reads/{preproc}/{fs_name}/profile/{fs_name}_{strand}_fastqc/fastqc_data.txt'
fastqc_zip_wc: '{prefix}/{df}/reads/{preproc}/{sample}/profile/{sample}_{strand}_fastqc.zip'
count_wc: '{prefix}/{df}/reads/{preproc}/{sample}/profile/{sample}_{strand}.count'

sample_dir_wc:    '{prefix}/{df}/reads/{preproc}/{sample}'
multiqc_fatqc_wc: '{prefix}/{df}/multiqc/{sample_set}/{strand}/samples.list'

dada2_err_wc: '{dada2_dir}/{sample_set}/err{strand}.rds'
dada2_merged_wc: '{prefix}/{df}/reads/{preproc}/{sample}/{sample}__{sample_set}.merged.rds'

sam_wc: ''

assembly_table_wc: '{prefix}/{df}/assembly/{assembler}__{params}/{sample_set}/sample_set.tsv'

metaphlan2_wc: '{prefix}/{df}/taxa/{preproc}/mp2__def{version}/{sample}/{sample}.mp2'