fastq_gz_file_wc: '{prefix}/{df}/reads/{preproc}/{sample}/{sample}_{strand}.fastq.gz'
sample_dir_wc: '{prefix}/{df}/reads/{preproc}/{sample}'
dada2_err_wc: '{dada2_dir}/{sample_set}/err{strand}.rds'
dada2_merged_wc: '{prefix}/{df}/reads/{preproc}/{sample}/{sample}__{sample_set}.merged.rds'