fastq_gz_file_wc: '{fs_prefix}/{df}/reads/{preproc}/{df_sample}_{strand}.fastq.gz'
fastq_gz_R1_wc: '{fs_prefix}/{df}/reads/{preproc}/{df_sample}_R1.fastq.gz'
fastq_gz_R2_wc: '{fs_prefix}/{df}/reads/{preproc}/{df_sample}_R2.fastq.gz'
fastq_file:       '{fs_prefix}/{df}/reads/{preproc}/{df_sample}/{df_sample}_{strand}.fastq'
md5_fastq_gz:     '{fs_prefix}/{df}/reads/{preproc}/{df_sample}/profile/{df_sample}_{strand}.md5'


sample_dir_wc:    '{fs_prefix}/{df}/reads/{preproc}/{df_sample}'
count_wc: '{fs_prefix}/{df}/profile/count/{preproc}/{df_sample}/{df_sample}_{strand}.count' 
